[package]
name = "error-handler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"

# trace
tracing = "0.1"
tracing-subscriber = "0.3"
